### ISSUE TITLE
Error on the grafana 3

### ISSUE THREAD

**Issue by elyulka** [percona/grafana-dashboards#2]
Tried to run on the grafana 3.0-beta5 and got error

```
Dashboard init failed
Template variables could not be initialized: b.metricFindQuery is not a function
```

Above error occurs if there is no datasources defined. After i added prometheus datasource above error does not show up but i get errors on most of the charts like:

1. "Multiple series error"
2. "Cannot read property '1' of null"

But these charts work: 
- "MySQL Network Usage Hourly"
- "Top Commands Counter Hourly"

**Comment by roman-vynar** [comment]
Hi, 

The dashboards work only for 2.6 because the patch is required, see https://github.com/percona/grafana-dashboards#apply-grafana-patch

Once 3.0 is released stable and no prometheus plugin improvement is implemented, there will be another instructions how to patch grafana with this interval fix.
