### ISSUE TITLE
Wrong graph for the flow control in 5.6

### ISSUE THREAD

**Issue by Tusamarco** [percona/grafana-dashboards#5]
Hi @roman-vynar  in the definition of the graph in the Galera dashboard the FLOW CONTOL graph and the GALERA PARALLELIZATION EFFICENCY one.
Both should use the function:
` rate(<metric>[$interval])`
This because the values from show global status from 5.6 on report an absolute counter. 
The resulting graphs is wrong:

**Comment by roman-vynar** [comment]
It was graphed this way because it was not an absolute counter initially because of this bug https://bugs.launchpad.net/galera/+bug/1180792
It was fixed only in 5.6 and Galera 3.x.

I agree we should change this to `rate()` (`delta()` is for gauges) because being as a gauge with 5.5 it was useless as any `SHOW STATUS` execution was resetting it.

**Comment by Tusamarco** [comment]
Actually Delta is better because I am testing rate and is not reporting 
the riight values while delta is.

------------------------------------------------
Marco Tusa,
Mobile: +1-613-282-7337
do something for your planet!
http://www.tusacentral.net/
------------------------------------------------
Save a tree... please don't print this e-mail unless you really need to

**Comment by Tusamarco** [comment]
that is weird but yes I can confirm rate is always reporting 0 while delta report the right values

**Comment by roman-vynar** [comment]
Changed to `rate()`, see [demo](https://pmmdemo.percona.com/graph/dashboard/db/pxc-galera-graphs?panelId=45&fullscreen).
